name: "Documentation: Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pyrobotstxt
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        
      - name: Create Virtual Environment
        run: python3.10 -m venv ./.venv
      
      - name: Build and Install pyrobotstxt[doc] into Virtual Environment
        run: python3.10 -m pip install .[doc]

      - name: Build HTML Documentation for pyrobotstxt
        run: . ./.venv/bin/activate && cd ./docs && make html

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ./docs/build/html/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Documentation Artifacts
        uses: actions/download-artifact@v4
        with:
          name: html-docs
          path: ./docs/build/html

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html