name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout pyrobotstxt
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        
      - name: Create Virtual Environment
        run: python3.10 -m venv ./.venv
      
      - name: Build and install pyrobotstxt[doc]
        run: python3.10 -m pip install .[doc]

      - name: Build HTML
        run: . ./.venv/bin/activate && cd ./docs && make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html